Create dockerfile
SlangLab-NU/VoiceCollector pull request #25
Opened 2023-08-25 19:59 UTC by macarious

Three Docker Files are created in the root directory (along with the configuration files):
1.  `Dockerfile.minio` for the MinIO storage,
2.  `Dockerfile.server` for the backend API, and
3.  `Dockerfile.web` for the frontend application.

Instructions to build and run the containers are found in DOCKER_README.md.

The web application has been tested by submitting a voice sample to the MinIO server through the backend API to ensure the three containers are communicating properly.

The voice sample has been successfully submitted:
![web-voice-submitted](https://github.com/SlangLab-NU/VoiceCollector/assets/63441014/4a4d94d4-458e-48db-b7a1-2722f7abc35d)

The voice sample has been saved successfully in the MinIO container:
![minio-container-local-s3](https://github.com/SlangLab-NU/VoiceCollector/assets/63441014/981115fb-39c7-42a9-8df4-b59aea3ec7c8)

The log shows that the backend API server is being called and requests are resolved properly:
```
2023-08-25 12:15:28 minio-container   | Formatting 1st pool, 1 set(s), 1 drives per set.
2023-08-25 12:15:28 server-container  |  * Serving Flask app '__init__.py'
2023-08-25 12:15:28 minio-container   | WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
2023-08-25 12:15:28 server-container  |  * Debug mode: off
2023-08-25 12:15:28 minio-container   | MinIO Object Storage Server
2023-08-25 12:15:28 server-container  | Level: INFO
2023-08-25 12:15:28 minio-container   | Copyright: 2015-2023 MinIO, Inc.
2023-08-25 12:15:28 server-container  | Time: 2023-08-25 19:15:28,960
2023-08-25 12:15:28 server-container  | Logger: werkzeug
2023-08-25 12:15:28 server-container  | Path: _internal:224
2023-08-25 12:15:28 server-container  | Function :_log
2023-08-25 12:15:28 minio-container   | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
2023-08-25 12:15:28 server-container  | Message: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2023-08-25 12:15:28 minio-container   | Version: RELEASE.2023-08-16T20-17-30Z (go1.19.12 linux/amd64)
2023-08-25 12:15:28 server-container  |  * Running on all addresses (0.0.0.0)
2023-08-25 12:15:28 server-container  |  * Running on http://127.0.0.1:5000
2023-08-25 12:15:28 server-container  |  * Running on http://172.19.0.3:5000
2023-08-25 12:15:28 server-container  | 
2023-08-25 12:15:28 server-container  | Level: INFO
2023-08-25 12:15:28 server-container  | Time: 2023-08-25 19:15:28,960
2023-08-25 12:15:28 server-container  | Logger: werkzeug
2023-08-25 12:15:28 minio-container   | 
2023-08-25 12:15:28 minio-container   | Status:         1 Online, 0 Offline. 
2023-08-25 12:15:28 server-container  | Path: _internal:224
2023-08-25 12:15:28 server-container  | Function :_log
2023-08-25 12:15:28 server-container  | Message: Press CTRL+C to quit
2023-08-25 12:15:28 server-container  | 
2023-08-25 12:15:31 server-container  | Level: INFO
2023-08-25 12:15:31 server-container  | Time: 2023-08-25 19:15:31,793
2023-08-25 12:15:31 server-container  | Logger: werkzeug
2023-08-25 12:15:31 server-container  | Path: _internal:224
2023-08-25 12:15:31 server-container  | Function :_log
2023-08-25 12:15:31 server-container  | Message: 172.19.0.2 - - [25/Aug/2023 19:15:31] "GET /api/v1/speak/get_reference HTTP/1.0" 200 -
2023-08-25 12:15:31 server-container  | 
2023-08-25 12:15:59 server-container  | Level: INFO
2023-08-25 12:15:59 server-container  | Time: 2023-08-25 19:15:59,986
2023-08-25 12:15:59 server-container  | Logger: speak
2023-08-25 12:15:59 server-container  | Path: length_check:9
2023-08-25 12:15:59 server-container  | Function :get_audio_length
2023-08-25 12:15:59 server-container  | Message: duration (s): 1.92
2023-08-25 12:15:59 server-container  | 
2023-08-25 12:15:59 server-container  | 000000000000000000000001111111111+(0.6900000000000004)111111111111111111111111111111-(1.8900000000000015)
2023-08-25 12:15:59 server-container  | Level: INFO
2023-08-25 12:15:59 server-container  | Time: 2023-08-25 19:15:59,988
2023-08-25 12:15:59 server-container  | Logger: speak
2023-08-25 12:15:59 server-container  | Path: silence_check:165
2023-08-25 12:15:28 minio-container   | S3-API: http://172.19.0.4:9000  http://127.0.0.1:9000 
2023-08-25 12:15:28 minio-container   | Console: http://172.19.0.4:35701 http://127.0.0.1:35701 
2023-08-25 12:15:28 minio-container   | 
2023-08-25 12:15:28 minio-container   | Documentation: https://min.io/docs/minio/linux/index.html
2023-08-25 12:15:59 server-container  | Function :get_silence_ratio
2023-08-25 12:15:59 server-container  | Message: Voiced frames count: 40
2023-08-25 12:15:59 server-container  | 
2023-08-25 12:15:59 server-container  | Level: INFO
2023-08-25 12:15:59 server-container  | Time: 2023-08-25 19:15:59,988
2023-08-25 12:15:59 server-container  | Logger: speak
2023-08-25 12:15:59 server-container  | Path: silence_check:166
2023-08-25 12:15:28 minio-container   | Warning: The standard parity is set to 0. This can lead to data loss.
2023-08-25 12:15:59 server-container  | Function :get_silence_ratio
2023-08-25 12:15:28 minio-container   | 
2023-08-25 12:15:59 server-container  | Message: Total frames count: 63
2023-08-25 12:15:28 minio-container   |  You are running an older version of MinIO released 6 days before the latest release 
2023-08-25 12:15:59 server-container  | 
2023-08-25 12:15:28 minio-container   |  Update: Run `mc admin update` 
2023-08-25 12:15:59 server-container  | Level: INFO
2023-08-25 12:15:28 minio-container   | 
2023-08-25 12:15:59 server-container  | Time: 2023-08-25 19:15:59,988
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: using the "epoll" event method
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: nginx/1.24.0
2023-08-25 12:15:28 minio-container   | 
2023-08-25 12:15:30 minio-container   | MinIO server is ready!
2023-08-25 12:15:59 server-container  | Logger: speak
2023-08-25 12:15:30 minio-container   | Added `myminio` successfully.
2023-08-25 12:15:59 server-container  | Path: silence_check:168
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023-08-25 12:15:30 minio-container   | Bucket created successfully `myminio/local-s3`.
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: OS: Linux 5.15.90.1-microsoft-standard-WSL2
2023-08-25 12:15:59 server-container  | Function :get_silence_ratio
2023-08-25 12:15:59 server-container  | Message: Silence ratio: 0.37
2023-08-25 12:15:59 server-container  | 
2023-08-25 12:16:00 server-container  | Level: INFO
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker processes
2023-08-25 12:16:00 server-container  | Time: 2023-08-25 19:16:00,019
2023-08-25 12:16:00 server-container  | Logger: werkzeug
2023-08-25 12:16:00 server-container  | Path: _internal:224
2023-08-25 12:16:00 server-container  | Function :_log
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker process 7
2023-08-25 12:16:00 server-container  | Message: 172.19.0.2 - - [25/Aug/2023 19:16:00] "POST /api/v1/speak/submit/test27.280904543172802.webm HTTP/1.0" 200 -
2023-08-25 12:16:00 server-container  | 
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker process 8
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker process 9
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker process 10
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker process 11
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [notice] 1#1: start worker process 12
2023-08-25 12:15:28 web-container     | 2023/08/25 19:15:28 [...]

2023-08-25 21:33 UTC, ztybigcat commented on Dockerfile.server
I encountered an error building the server, seems has to do with missing keys for apt
```
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

2023-08-25 21:37 UTC, ztybigcat commented on Dockerfile.web
I encountered some errors when building the images:
```
Step 5/17 : COPY ./yarn.lock ./
COPY failed: stat /var/lib/docker/tmp/docker-builder020478843/yarn.lock: no such file or directory
```

2023-08-25 21:39 UTC, ztybigcat requested changes
Encountered some errors while building server and web.
Please see individual file comments.

2023-08-28 17:00 UTC, macarious commented on Dockerfile.web
This may possibly be cause by the missing `yarn.lock` file. There are two things here:

## 
1. This line in the `Dockerfile.web` is referring to the incorrect directory, so I will change it to the appropriate directory instead (`/web`):
```
COPY ./yarn.lock ./
```
```
COPY ./web/yarn.lock ./
```
2. The file `yarn.lock` is currently included int he `.gitignore`; I will remove it from there so the file will be pushed to the repository. The file should be available once you pull the latest version.

I could not reproduce the exact same error message. This may be because I am using a different operating system, but this is what I encountered when I removed my yarn.lock:
```
 => ERROR [build 4/8] COPY ./web/yarn.lock ./                                                                                                                                                                                                                                            0.0s 
------
 > [build 4/8] COPY ./web/yarn.lock ./:
------
Dockerfile.web:14
--------------------
  12 |     # Copy package.json and package-lock.json
  13 |     COPY ./web/package.json ./
  14 | >>> COPY ./web/yarn.lock ./
  15 |     COPY ./web/src ./src
  16 |     COPY ./web/public ./public
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 6c6c09bd-0849-41ef-8231-4e06758c72fa::t5jqs4z0fhjf7051zzntlysry: "/web/yarn.lock": not found
```

2023-08-28 18:28 UTC, ztybigcat commented on Dockerfile.web
Verified build server using another system, error is resolved.
Verified build web and the issue is fixed.
Verified app running with docker-compose.

2023-08-28 18:29 UTC, ztybigcat approved these changes
Tested app running smoothly using docker-compose

2023-08-29 17:21 UTC, merged