2 add a sql database for running app locally
SlangLab-NU/VoiceCollector pull request #9
Opened 2023-06-14 23:30 UTC by jordan-git-lewis

The database runs locally in its current state.
Known issues:
in speak.py line 56 - DB is created here initially, but then it gets commented out to not overwrite the previous data.
in speak.py line 64 - References are written to DB here. This will execute every time the program is run, which is unnecessary

2023-06-15 18:26 UTC, aanchan requested changes

2023-06-15 18:26 UTC, aanchan commented on server/app/api/speak.py
> +        print("Write_Record_Route local occured")
I would not necessarily print things, but log using the logger module. I am not sure if this is consistent across the code base. If not, we could make a Github issue for it.

2023-06-15 18:26 UTC, aanchan commented on server/app/api/speak.py
> +    # conn = db_helper.get_db_connection()
I would remove this as it is a stray comment.

2023-06-15 18:26 UTC, aanchan commented on server/app/scripts/db_helper.py
> +
These commented lines could be removed

2023-06-15 18:26 UTC, aanchan commented on server/app/scripts/db_helper.py
> +    #     print(row)
These commented lines could also be removed

2023-06-15 18:26 UTC, aanchan commented on server/app/scripts/db_helper.py
>  def connect_to_ec2():
This method does have a conflict from a base branch, and the original MYSQL connections seem to have been removed. We could have the best of both worlds here and have it connect to a local db on a later ticket.

Currently, connect_to_ec2, isn't this duplicated code which is the same as write_references_to_db?  If it is necessary, we could rename it to something more meaningful.

2023-06-15 18:26 UTC, aanchan commented on server/app/scripts/referencesDB.py
Do we need this referencesDB.py gives that we read from a text file and write to the database? If it is duplicate code maybe we can delete it?

2023-06-15 18:26 UTC, aanchan commented on server/app/database.db
We should probably not commit the .db file

2023-06-16 01:50 UTC, Rao2321 commented
1. moving all the names like database.db, schema.sql and other configurables to config file
2. validating the input before inserting into the database
3. having a check like if else if it is dev/local env and if the db exists and having else with creating db, because if X tries to clone the code and try to run it hsould ideally create the db without uncommenting
4. and some unit test cases, from my understanding there are no unittesting code for db utils or connections i see only test cases for api, data utils and validations. this also includes testing connections to aws

2023-06-16 20:12 UTC, jordan-git-lewis commented
> 1. moving all the names like database.db, schema.sql and other configurables to config file
> 2. validating the input before inserting into the database
> 3. having a check like if else if it is dev/local env and if the db exists and having else with creating db, because if X tries to clone the code and try to run it hsould ideally create the db without uncommenting
> 4. and some unit test cases, from my understanding there are no unittesting code for db utils or connections i see only test cases for api, data utils and validations. this also includes testing connections to aws

Updated the config.json to have variable names separated by APP and DATABASE. The program now pulls from that file accordingly, but let me know if there is a better way to write this

2023-06-19 18:11 UTC, aanchan commented
Can add a TYPE variable to config.json in the DATABASE field to:
   -  unify the connect_to_ec2 and connect_to_local_db_methods
    - And unify the write_to_db and write_local_record method

2023-06-19 18:21 UTC, aanchan commented on server/app/database.db
Remove the .db file

2023-06-19 18:24 UTC, aanchan commented on server/app/scripts/db_helper.py
> +config = json.loads(config_path.read_text())
Add a with open here

2023-06-20 02:21 UTC, merged